mysite/login/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from login import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^login/$', views.registereduser,name='registereduser'),
    url(r'^$', views.homepage,name='homepage'),
    url(r'^home/$', views.homepage,name='homepage'),
    url(r'^upload/$',views.uploadimage),
    url(r'^getbikes/$',views.getbikes),
    #url(r'^getselectedbike/$',views.getselectedbike),
    url(r'^submitimage/$',views.submitimage,name='submitimage'),
    #url(r'^single/$', views.homepage,name='homepage'),
    url(r'^mybike/$',views.mybike,name='mybike'),
    url(r'^getselectedbike/(?P<bikeid>[0-9]+)/$',views.getselectedbike,name='getselectedbike'),
]

urlpatterns = format_suffix_patterns(urlpatterns)
urlpatterns += staticfiles_urlpatterns()

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('login.urls',namespace="login")),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views

template_name = {'template_name': 'rest_framework/login.html'}

app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

mysite/rest_framework/utils/urls.py
from django.utils.six.moves.urllib import parse as urlparse


def replace_query_param(url, key, val):
    """
    Given a URL and a key/val pair, set or replace an item in the query
    parameters of the URL, and return the new URL.
    """
    (scheme, netloc, path, query, fragment) = urlparse.urlsplit(url)
    query_dict = urlparse.parse_qs(query, keep_blank_values=True)
    query_dict[key] = [val]
    query = urlparse.urlencode(sorted(list(query_dict.items())), doseq=True)
    return urlparse.urlunsplit((scheme, netloc, path, query, fragment))


def remove_query_param(url, key):
    """
    Given a URL and a key/val pair, remove an item in the query
    parameters of the URL, and return the new URL.
    """
    (scheme, netloc, path, query, fragment) = urlparse.urlsplit(url)
    query_dict = urlparse.parse_qs(query, keep_blank_values=True)
    query_dict.pop(key, None)
    query = urlparse.urlencode(sorted(list(query_dict.items())), doseq=True)
    return urlparse.urlunsplit((scheme, netloc, path, query, fragment))

mysite/login/models.py
from django.db import models
from django.conf import settings

class Bikes(models.Model):
       
        bikename= models.CharField(max_length=100,blank=True,default=False)
        bikeid = models.CharField(max_length=100,blank=True)
        bikeimage = models.ImageField(upload_to='static/images',null=True, max_length=255)
        rentbelow12  = models.CharField(max_length=100,blank=True)
        rentbelow15 =  models.CharField(max_length=100,blank=True)
        rentmorethan15 = models.CharField(max_length=100,blank=True)
        
        def __str__(self):
                return self.bikename

class Register(models.Model):
    name = models.CharField(max_length=100,blank=True)
    mobilenumber = models.CharField(max_length=100)
    dlno = models.CharField(max_length=100)
    password= models.CharField(max_length=1000)
    


    def __str__(self):
        return self.name

mysite/login/views.py
from __future__ import unicode_literals
from rest_framework import status
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.shortcuts import render
from login.models import Bikes
from login.serializers import BikeSerializer
from django.shortcuts import render




def homepage(request):
    return render(request, 'index.html')

def mybike(request):
    return render(request, 'localtest.html')

def uploadimage(request):
    return render(request, 'upload.html')

@api_view(['GET','POST'])
def submitimage(request):
    if request.method == 'POST':
       serializer = BikeSerializer(data=request.data )
       if serializer.is_valid():
          serializer.save()
          return Response(serializer.data, status=status.HTTP_201_CREATED)
       return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET','POST'])
def getbikes(request):
    if request.method == 'GET':
        products = Bikes.objects.all()
        serializer = BikeSerializer(products,many=True )
        s={"records":serializer.data}
        print("bikes====>",s);
        return Response(s,status=status.HTTP_201_CREATED)

@api_view(['GET','POST'])
def getselectedbike(request,bikeid):
    visitors = Bikes.objects.get(bikeid=bikeid)
    
    serializer = BikeSerializer(visitors)
    
    s={"records":serializer.data}
    
    return Response(s)



@api_view(['GET','POST'])
def getselectedbikes(request):
    if request.method == 'POST':
        products = Bikes.objects.get(bikename=request.data['bikename'])
        serializer = BikeSerializer(products,many=True )
        s={"records":serializer.data}
        return Response(s,status=status.HTTP_201_CREATED)
    return Response('yha')




@api_view(['GET','POST'])
def registration(request):
    
 
    return Response(
    'register unsuccessful',
  
    )


@api_view(['GET', 'POST'])
def registereduser(request):
    """
    List all snippets, or create a new snippet.
    """
    
    return Response("lkasdsnfns")

mysite/login/templates/homepage.html
<div class="slide story" id="slide-1" data-slide="1" style="">
		<div class="container">
			<div id="home-row-1" class="row clearfix">
				<div class="col-12">
					<h1 class="font-semibold">FLYBAXI <span class="font-thin">DESIGN</span></h1>
					<h4 class="font-thin">We are an <span class="font-semibold">independent interactive agency</span> based in Jaipur</h4>
					<br>
					<br>
				</div><!-- /col-12 -->
			</div><!-- /row -->
			<div id="home-row-2" class="row clearfix">
				<div class="col-12 col-sm-4"><div class="home-hover navigation-slide" data-slide="4"><img src={% static 'images/s02.png' %}></div><span>PLAN</span></div>
				<div class="col-12 col-sm-4"><div class="home-hover navigation-slide" data-slide="3"><img src={% static 'images/s02.png' %}></div><span>PICK</span></div>
				<div class="col-12 col-sm-4"><div class="home-hover navigation-slide" data-slide="5"><img src={% static 'images/s03.png' %}></div><span>RIDE</span></div>
			</div><!-- /row -->
		</div><!-- /container -->
	</div><!-- /slide1 -->
	
	<!-- === Slide 2 === -->
	<div class="slide story" id="slide-2" data-slide="2">
		<div class="container">
			<div class="row title-row">
				<div class="col-12 font-thin">


 <span class="font-semibold">Your four step journey to an awesome ride!</span></div>
			</div><!-- /row -->
			<div class="row line-row">
				<div class="hr">&nbsp;</div>
			</div><!-- /row -->
			<div class="row subtitle-row">
				<div class="col-12 font-thin">This is what <span class="font-semibold">we do best</span></div>
			</div><!-- /row -->
			<div class="row content-row">
				<div class="col-12 col-lg-3 col-sm-6">
					<p><i class="icon icon-eye-open"></i></p>
					<h2 class="font-thin">Freeee <span class="font-semibold">Booking</span></h2>
					<h4 class="font-thin">Book a vehicle in less than a minute .</h4>
				</div><!-- /col12 -->
				<div class="col-12 col-lg-3 col-sm-6">
					<p><i class="icon icon-laptop"></i></p>
					<h2 class="font-thin">Assured <span class="font-semibold">Quality</span></h2>
					<h4 class="font-thin">All our vehiles are new and go through strictest service schedule. </h4>
				</div><!-- /col12 -->
				<div class="col-12 col-lg-3 col-sm-6">
					<p><i class="icon icon-tablet"></i></p>
					<h2 class="font-thin">Lowest <span class="font-semibold">Price</span></h2>
					<h4 class="font-thin">Hire a motorcycle lower than our quoted price and get a ride with us for free.</h4>
				</div><!-- /col12 -->
				<div class="col-12 col-lg-3 col-sm-6">
					<p><i class="icon">
					<img style="width:80px;height:80px; " src= {% static 'images/racing.svg' %}/>
					</i>  </p>
					<h2 class="font-thin">Free <span class="font-semibold">Helmet</span></h2>
					<h4 class="font-thin">Safety comes first for FlyBaxi. We provide complimentary helmets for each ride.</h4>
				</div><!-- /col12 -->
			</div><!-- /row -->
		</div><!-- /container -->
	</div><!-- /slide2 -->

mysite/login/templates/localtest.html
<html>
<head><title>SignUp</title>
</head>

<body>
    <div class="form">
    <form action="{% url 'login:getselectedbike' %}" method="post">
    {% csrf_token %}
        PhoneNumber<input type="text" name="bikename" size="20"><br />
      
        <input type="submit" value="submit" />
    </form>
</body>
</html>
Chat conversation end
Type a message...

mysite/login/templates/upload.html
<html>
<head><title>UploadImage</title>
</head>

<body>
    <form action="{% url 'login:submitimage' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        BikeId:<input type="text" name="bikeid" size="20"><br/>
        BikeName<input type="text" name="bikename" size="20"><br />
        Image<input type="file" name="bikeimage" accept="image/* value="fileupload"><br />
        rentbelow12<input type="text" name="rentbelow12" size="20"><br />
        rentbelow15hrs<input type="text" name="rentbelow15" size="20"><br />
        rent more than 15 hr<input type="text" name="rentmorethan15" size="20"><br />
        
        <input type="submit" value="submit" />
    </form>
</body>
</html>